### PR TITLE
Issue13

### PR DESCRIPTION
**Pull request by dnadeau4**

### CODE REVIEW

**Comment by dnadeau4** [comment]
Tanya found out that we missed this file somehow when we merged.  It was a new one she created from issue#13.

**Comment by dnadeau4** [comment]
I have restored dosctanya just in case we find more.  It most have been deleted when we add and move genutil/cdutil

**Comment by dnadeau4** [comment]
There is only 1 file changed right?

**Comment by davis278** [comment]
One of the commits in this pull request, 9f01880, says 520 files have been changed. I've attached the screenshot of that commit. I'm thinking that the 9f01880 commit (use file from master) is when you restored the dosctanya branch (to get the one file that we need to add), but it is restoring all the files from that branch which means your subsequent edits (of which there are many) will be lost - assuming I'm understanding things correctly.

Screen Shot 2019-06-28 at 10 28 21 AM

**Comment by dnadeau4** [comment]
@davis278  and I merge master into issue13 after that to which means that issue13 https://github.com/CDAT/Jupyter-notebooks/commit/9f01880595ce5245926f6f62b43de46be1fc16bf which means that https://github.com/CDAT/Jupyter-notebooks/pull/32/commits/d73b11fd2c302f38e6eeda98a1e7013ab76f02c1  was already in master logs and only 1 file was changed after that.  That is what github.com is telling you at the top.  

I just try the "command line instructions" and do a `git diff master` after step 1 and saw that only 1 file has been changed.  It is the last commit that counts

**Comment by davis278** [comment]
@dnadeau4 thanks for the clarification. I've followed the command line steps and can see that only one file has changed. I'll approve the pull request.

**Pull request merged**
