### PR TITLE
Changes to Section 2

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@davis278 this looks good to me (I would have kept the output, but it's fine), please let me know if it works for you as well.

**Comment by doutriaux1** [comment]
@reshel3 @davis278 should we generate the htmls as well?

**Comment by reshel3** [comment]
I will generate the html's and let you know when I'm done so you can merge my branch if that is ok..:)

**Comment by doutriaux1** [comment]
@reshel3 @davis278 is that the one we want to merge in master?

**Comment by davis278** [comment]
Yes, @doutriaux1, these commits are ready to be merged into master since @reshel3 and @dnadeau4 moved the CDUtils and GenUtils notebooks to their own branches. 

Please approve this branch first before approving the CDUtils and GenUtils branches. We can make further refinements once this branch has been merged into master.

**Comment by doutriaux1** [comment]
@davis278 the issue is that this PR DELETES EVERY FILE IN THE REPO. I can't merge this!

**Comment by dnadeau4** [comment]
It does not delete every files,  for example:
vcsaddons/EzPlot_Example/EzPlot_Example.html
is still there.  

I deleted a lot of "mp4" and "png"s that were not used, I can put them back if you want. 

Can you tell me what files are missing or directory?

**Comment by doutriaux1** [comment]
@dnadeau4 only the detrend seems to be deleted somehow, tne rest is "large diff" which i confused with some more delted files.

**Comment by dnadeau4** [comment]
I'll clean this up right now.

**Pull request merged**
