### PR TITLE
Taylor update

### PR DESCRIPTION
**Pull request by davis278**
There are quite a few changes here (from both Tanya and me).

Three questions:
1) I don't see a difference between the plots where the x and y offset are used and when they are not used. There are two places where x and y offsets are applied and both of those diagrams look the same to me as the diagram right before them where no offset is applied. Am I missing something or are the offsets not working?
2) Recommendations regarding the reference point: 
a) Use the same reference point for all plots (e.g. B1) and keep the black reference line for all plots once you've introduced it (we can add a comment to explain what that line of code is doing - # puts reference line at 1.2 - or something similar). 
b) After looking at figures 10 and 11 in Karl's paper, shouldn't the isolines curve around the reference point which is at an isoline of 1? (I know it is dummy data, but if there is a way to easily make our plots look closer to figs. 10 and 11 in Karl's paper, that would be good...)
3) I'm guessing there isn't anything we can do about the small black dot to the right of the diagram (which your vertical legend nicely covers). Is that true?

Thanks for reviewing, Jiwoo!

### CODE REVIEW

**Comment by doutriaux1** [comment]
@davis278 The ids are gone! @scottwittenburg I'll take a look at this tomorrow but I will likely need your help!

**Comment by doutriaux1** [comment]
@davis278 also in the notebook there is no more images when we open it. Please make sure to run it fully and save the notebook. If you accidentally hit `clear cells` we lose the pix.

**Comment by scottwittenburg** [comment]
I'm happy to help however I can @doutriaux1, though I don't know what you mean by "the ids are gone".

**Comment by doutriaux1** [comment]
If you run the notebooks, next to the symbols we're supposed to have a text wirth the id (the id shows up in the legend). e.g `A1`

**Comment by scottwittenburg** [comment]
Ah, I see, I remember those now.  But they must still be getting rendered in the vcs tests, right?

**Comment by doutriaux1** [comment]
I'm not sure honestly. I'll double check the baselines for our td tests. This is a much more extensive test of the taylor diagrams though.

**Comment by scottwittenburg** [comment]
I see them right now in many of the baselines of `uvcdat-testdata` on the `master` branch.

**Comment by davis278** [comment]
If by ids @doutriaux1, you mean line numbers, the missing line numbers and missing output images are intentional. 

@dnadeau4 recommended, once I'm done with my edits and ready to push to the remote server, I should restart the kernel and clear all outputs (on my local machine and branch), save the notebook, commit and push to the remote server (using my own branch: taylor_update). Then once the merge has been approved, merge into master, THEN run the notebook to get the output and line numbers and then create the html file. This avoids having conflicts when merging - @dnadeau4 can provide more details since I've never experienced it, but it makes sense sine the checkpoints file and perhaps the binary code for the output images is different in my version even if the output looks identical to the version before I started my documentation edits.

If we want to adopt a different strategy, let me know.

**Comment by davis278** [comment]
Ah - sorry, I should have read the comments more closely.  Yes, the ids are not showing up. In all my running of the notebook yesterday, I did not see them.  @lee1043 and I updated the notebook from python 2 to python 3 yesterday so I'm wondering if the missing ids are the result of something that worked in python 2 not working in python 3?

**Comment by dnadeau4** [comment]
@davis278 This is what is in Tanya env
```
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py27_1    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py27_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py27_1000    conda-forge
jupyter_latex_envs        1.4.4                 py27_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py27_0    conda-forge
```

**Comment by doutriaux1** [comment]
Ok someone should test that the TOC works in notebook under jupterlab, it's not a biggy if not but would be nice.

C.

**Comment by dnadeau4** [comment]
It does not work under "jupyter lab" but "jupyter notebook".  It is only to edit documentation so it is ok.

**Comment by doutriaux1** [comment]
I think it's fine too.

**Comment by davis278** [comment]
@dnadeau4 and @doutriaux1 here are the jupyter elements that are in my environment:
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py36_1000    conda-forge
jupyter_latex_envs        1.4.4                 py36_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py36_0    conda-forge

The main difference I see in the extensions between my environment and Tanya's is that I'm using python 3.6 and Tanya is using 2.7.

Do you think this will be a problem? 

Will any of the other differences (in jupyter_client and console) cause problems, do you think?

**Comment by doutriaux1** [comment]
@davis278 I figured out the issue in cdat 8.1 we fixed a bug where the font size was not constant depending on the units of the plot. With the fix in I forgot to update this tutorial that was generated with UVCDAT 2.12.

Please review my changes. Also at the end the last cell talks about controling via template, we'll need to link to the template tutorial

**Comment by doutriaux1** [comment]
@davis278 do you think we can merge this?

**Pull request merged**
