### PR TITLE
vcs tempaltes tutorial

### PR DESCRIPTION
**Pull request by doutriaux1**
@davis278 this is the vcs templates that should probably linked to from 99% of other VCS tutorials.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@davis278 here it is

**Comment by doutriaux1** [comment]
@davis278 any progress on this?

**Comment by davis278** [comment]
I've reviewed the EzTemplate notebook (in the vcsaddons folder) and while I like the new table of contents (TOC), I think that TOC was created before we settled on not including the numbers in the TOC. @reshel3  has a version of this notebook in her dosctanya branch which has a TOC that matches the style of the TOCs for all the rest of the notebooks, so I'd vote on using @reshel3 's version.  I've tested the code from @reshel3 's version and it looks good (there was one mistake, but Tanya fixed that this afternoon, though she hasn't yet created a matching .html file as of 4:30 pm May 30, 2019.)

Three other observations:
1. Both this version and and @reshel3's dosctanya version are using Python 2. Is it worth updating to Python 3 for this notebook or waiting until we do all the notebooks to Python 3?
2. There are a few typos, but I can fix those after this latest version is pushed to master since that seems simpler.
3. For some reason the output of the Multiple.list() line of code is formatted better in your version of the notebook compared to my running of @reshel3 dosctanya code. (Yours has indentation that mine does not have.) 
Screen Shot 2019-05-30 at 4 38 22 PM

Are you OK using @reshel3 's dosctanya version?

**Comment by davis278** [comment]
Previous comment pertained to EzTemplate notebooks which has been updated, however this pull request really addresses the VCS_Templates.ipynb which has now been reviewed and edited to improve grammar and the logical flow of steps (only two steps toward the end have been split and reordered). 

Ready for review by @doutriaux1. 

I will update the Tutorials.html page on the CDAT website and will create a pull request in that repo to display this new VCS_Templates.ipynb (and its corresponding .html page) on the CDAT Tutorials page.

**Comment by davis278** [comment]
One other comment: 
I changed the following code:
template.data.y1 = .55  # 55% from bottom
template.data.y2 = .95  # 5% from top (or 95% from bottom) 
to
template.data.y1 = .45  # 45% from bottom
template.data.y2 = .85  # 15% from top (or 85% from bottom)
because the concept is still illustrated, but the resulting map does not draw on top of text at the top of the plot that would be helpful to read as users are learning about all the aspects they can modify.

**Comment by davis278** [comment]
Since I want to share this notebook with Ken Sperber, I am going to merge the changes and if we need to change something next week, I'm happy to do that.

**Pull request merged**
